/* 
 * Jugugu密钥Fast模式
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject2Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject2
        //private InlineObject2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject2
            //instance = new InlineObject2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject2
        /// </summary>
        [Test]
        public void InlineObject2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject2
            //Assert.IsInstanceOf(typeof(InlineObject2), instance);
        }


        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Test]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Test]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Test]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'Paymentpass'
        /// </summary>
        [Test]
        public void PaymentpassTest()
        {
            // TODO unit test for the property 'Paymentpass'
        }
        /// <summary>
        /// Test the property 'Openid'
        /// </summary>
        [Test]
        public void OpenidTest()
        {
            // TODO unit test for the property 'Openid'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Unsigntxjson'
        /// </summary>
        [Test]
        public void UnsigntxjsonTest()
        {
            // TODO unit test for the property 'Unsigntxjson'
        }
        /// <summary>
        /// Test the property 'Chaintype'
        /// </summary>
        [Test]
        public void ChaintypeTest()
        {
            // TODO unit test for the property 'Chaintype'
        }

    }

}
