/* 
 * Jugugu密钥Fast模式
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2001
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2001Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2001
        //private InlineResponse2001 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2001
            //instance = new InlineResponse2001();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2001
        /// </summary>
        [Test]
        public void InlineResponse2001InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse2001
            //Assert.IsInstanceOf(typeof(InlineResponse2001), instance);
        }


        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Confluxaddress'
        /// </summary>
        [Test]
        public void ConfluxaddressTest()
        {
            // TODO unit test for the property 'Confluxaddress'
        }
        /// <summary>
        /// Test the property 'Ethaddress'
        /// </summary>
        [Test]
        public void EthaddressTest()
        {
            // TODO unit test for the property 'Ethaddress'
        }
        /// <summary>
        /// Test the property 'Paymentpassword'
        /// </summary>
        [Test]
        public void PaymentpasswordTest()
        {
            // TODO unit test for the property 'Paymentpassword'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Test]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

    }

}
